### ISSUE TITLE
Confine to a context

### ISSUE THREAD

**Issue by nathanbowser** [SpiderStrategies/bootslide#4]
Right now multiple bootslides on the page would blow up.

**Comment by nathanbowser** [comment]
@jerryorr I just noticed this open issue. Dash no longer uses this. I would think Sb3 has multiple bootslides on the same page? If so, we can probably close this if it's not a real problem

**Comment by jerryorr** [comment]
I don't know of any scenario where we would have more than one active bootslide, so yeah, until this is a problem, we can close it.
